fullsuite-se/ats-backend

src/controllers/analytic/graphsController.js
src/controllers/notification/notificationController.js
src/routes/analytic/graphsRoutes.js

feat: add application trend endpoint to retrieve monthly applicant tracking data to be used by FS team.

merge to dev (staging)

---

src/controllers/applicant/updateStatusController.js

merge fix relating to update status

merge the fix 

---

src/controllers/applicant/updateStatusController.js
src/controllers/notification/notificationController.js

fix the update_at issue relating to updateStatus

new PR to fix updated_at

---

src/controllers/applicant/updateStatusController.js

fix: update updateStage to return "PRE_SCREENING" for NONE status.

fix: update stage 

---

src/controllers/email/emailController.js
src/routes/email/emailRoutes.js

added an endpoint for adding and retrieving email templates.

feat: endpoint for adding and retrieving templates. 

---

src/controllers/applicant/addApplicantController.js

include test_result in sql statement

fix: add test_result in sql insert

---

src/controllers/applicant/applicantController.js

data for export

---

src/controllers/applicant/editApplicantController.js

🚀 LETSSS GOOOOOOO, users can now add additional contact information to applicants

refactor: improve SQL query formatting in editApplicantController

---

src/controllers/analytic/metricsController.js
src/routes/analytic/metricsRoutes.js

add endpoint to get count of applicants from FS website as requested by the FS team.

feat: add endpoint to get count of applicants from FS website

---

src/controllers/applicant/addApplicantController.js
src/controllers/applicant/applicantController.js
src/controllers/interview/interviewController.js
src/routes/user/userRoutes.js

Fix errors in backend relating to discussion feature

Fix errors in backend relating to discussion feature

---

src/controllers/applicant/applicantController.js

fix: fix the issue relating source of created_at data

fix: fix the issue relating source of created_at data

---

src/controllers/applicant/addApplicantController.js
src/controllers/email/emailController.js
src/routes/applicant/addApplicantRoutes.js

added a blacklist check for applicants from FS website. Will email applicants if he/she is blacklisted otherwise, the application will proceed to insert into  the database.

Add Blacklist check for FS website

---

src/controllers/applicant/addApplicantController.js
src/controllers/company/positionController.js
src/models/position/positionModel.js

refactor: refactor applicant insertion logic to map position titles o IDs and enhance error handling

Refactor code

---

src/controllers/applicant/addApplicantController.js

- Remove the pushed changes earlier that caused error. 
- Initiated the fix involving the adding of applicant from ATS, i.e., the created_at and updated_by should be the user who is login.

Applicant Insertion fix

---

src/app.js

fix: disable cors protection from FS website.

fix: disable cors protection from FS website.

---

src/app.js
src/controllers/userConfiguration/userConfigurationController.js
src/models/userConfiguration/smtpModel.js
src/routes/userConfiguration/userConfigurationRoutes.js

add total hires and breakdown of sources in f_InternalExternalHires function

Add smtp credentials

---

src/controllers/applicant/applicantController.js

add emails and contact numbers available when searching for applicant

feat: add email and contact number in search query

---

src/controllers/applicant/applicantController.js

fixed filter applicant date applied not shown correctly

---

src/controllers/applicant/applicantController.js

Co-authored-by: DarcMattz <johnvirgilcarvajal@gmail.com>
Co-authored-by: TonYacapin <yacapinton@gmail.com>

Fix date filter

---

src/models/userConfiguration/smtpModel.js

fix:add or update existing smtp

---

src/controllers/analytic/graphsController.js

enhance application trend query to include year and month number

feat: enhance application trend query to include year and month number

---

src/controllers/jobs/jobController.js
src/models/jobs/jobModel.js
src/routes/jobs/jobRoutes.js

modified jobs count

---

src/controllers/jobs/jobController.js
src/models/jobs/jobModel.js
src/routes/jobs/jobRoutes.js

added search route

---

src/controllers/jobs/jobController.js
src/models/jobs/jobModel.js
src/routes/jobs/jobRoutes.js

added filter for closed jobs

---

src/controllers/jobs/jobController.js

modified updateJob

---

src/controllers/email/emailController.js
src/models/applicant/applicantModel.js
src/routes/email/emailRoutes.js

add emailApplicantTestAssessment function to send assessment emails. The message is hardcoded for now.;

add email assessment endpoint

---

src/controllers/jobs/jobController.js

modified add job

---

src/controllers/applicant/addApplicantController.js
src/models/applicant/applicantModel.js

Duplicate applicant

---

package-lock.json
package.json
src/controllers/interview/interviewController.js
src/services/slack.js

integrate slack using api to notify new interviews and notes.

Slack integration

---

src/controllers/analytic/metricsController.js
src/models/analytic/metricModel.js

feat: add reason for rejection metric to analytics

feat: add reason for rejection metric to analytics

---

src/controllers/applicant/applicantController.js

fix: enhance applicant search to include full name matching

---

src/controllers/counter/applicantCounterController.js
src/models/applicant/applicantModel.js

refactor: streamline applicant count logic and improve status mapping
